import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { connectWallet } from '../components/web3connect'
import { useRouter } from 'next/router';


export default function Home() {

  const router = useRouter();

  async function verifyUser() {
    const output = await connectWallet()
    if (output === 0) {
      router.push('/denied')
    }
    else {
      router.push('/welcome')
    }
  }

  return (
    <div className={styles.container} >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      
        <h1 className={styles.title}>
          Connect to App <button style={{fontSize:'25px',padding:"2px"}} onClick={verifyUser}>CONNECT WALLET</button>
        </h1>
      
       
    </div>
  )
}